### ISSUE TITLE
Ma fonction a l'air bien trop complexe

### ISSUE THREAD

**Issue by MathildeChan** [MathildeChan/ember-tds#1]
Ma fonction pour enregistrer les stories me semblent très longues et compliquées

https://github.com/MathildeChan/ember-tds/blob/7be0db29e2b175ec63bbd4964168ae06dbcd9874/app/routes/story/new.js#L14-L24

**Comment by jcheron** [comment]
Je confirme...
A priori, il suffit d'affecter le projet à sty.project, et ensuite de faire un save sur sty...
```javascript
 save:function(sty, project) {  
  let store = this.get('store');
  let story=store.createRecord('story', sty);
  story.set('project', project);
  story.save().then(() =>transitionTo('project',project.id)); 
 }
```
Pas testé, c'est pour le principe...

**Comment by MathildeChan** [comment]
J'ai testé ça auparavant, ça ne fonctionnait pas

**Comment by jcheron** [comment]
Alors laissez ouvert,
On regardera après
Refaîtes un ping si j'oublie
