### ISSUE TITLE
Problème d'enregistrement

### ISSUE THREAD

**Issue by MathildeChan** [MathildeChan/ember-tds#2]
Enregistrement encore impossible, cette fois-ci le problème vient de transitionTo qui n'est pas considéré comme une fonction

https://github.com/MathildeChan/ember-tds/blob/7b69caa4c0cd40a089896b85eb0273fa0bd29a1e/app/routes/story/new.js#L13-L25

**Comment by jcheron** [comment]
`this.transitionTo()`?

**Comment by MathildeChan** [comment]
![image](https://user-images.githubusercontent.com/46043860/77080654-d6382b80-69f9-11ea-80f6-8baeae5c2264.png)

**Comment by MathildeChan** [comment]
Les stories se créent mais il n'y a ni redirection, ni affichage

**Comment by MathildeChan** [comment]
Problème résolu !

**Comment by jcheron** [comment]
Pour prendre de bonnes habitudes, 
il faut que vous mettiez la résolution...
