### ISSUE TITLE
Filter non fonctionnel ou array vide

### ISSUE THREAD

**Issue by MathildeChan** [MathildeChan/ember-tds#3]
https://github.com/MathildeChan/ember-tds/blob/600b70d0de6d6b43f682901b9e4895bc02702103/app/routes/project/board.js#L7

J'ai rajouté des stories à mes steps. L'épreuve qu'il me reste à affronter est celle de récupérer les stories qui sont en lien direct avec le projet dans lequel je suis, c'est pourquoi je souhaite utiliser la fonction filter(). Malheureusement, le tableau renvoyé est vide...

**Comment by jcheron** [comment]
Mais elles y sont déjà les stories dans le project, pourquoi aller les chercher à nouveau ?
C'est déclaré dans vos models:
https://github.com/MathildeChan/ember-tds/blob/600b70d0de6d6b43f682901b9e4895bc02702103/app/models/project.js#L1-L10

Vous avez bien ajouté l'adapter pour sérialiser les stories dans le projet ?
see [project adapter](https://slamwiki.kobject.net/richclient/emberjs/td4#ajout_d_un_adapter_pour_la_serialisation_des_stories_d_un_projet)

**Comment by MathildeChan** [comment]
J'ai du mal à exprimer mes idées... Finalement mon problème est que je ne sais pas comment dire quelles sont les stories qui sont dans mes steps.. J'ai peur que si je mette des stories dans mes steps cela regroupe l’entièreté de mes stories et que je ne puisse pas faire la différence entre celles du projet et celles des autres projets. C'est pourquoi je pensais utiliser filter... Mais je n'arrive pas à comprendre sur quoi je dois filtrer mes stories pour les afficher dans le bon step du bon projet...
C'est dur à expliquer...

**Comment by jcheron** [comment]
mais, une story n'appartient qu'à un seul projet, les stories ne sont pas partagées

**Comment by MathildeChan** [comment]
Cette erreur n'a plus lieu d'être depuis la modification du code ! Merci pour votre aide
