### ISSUE TITLE
[Board][MoveStep] Argument inutile + pas de parcours des stories de chaque step

### ISSUE THREAD

**Issue by jcheron** [MathildeChan/ember-tds#4]
Je signale les problèmes en plusieurs issues.

https://github.com/MathildeChan/ember-tds/blob/600b70d0de6d6b43f682901b9e4895bc02702103/app/templates/project/board.hbs#L41-L43

2 problèmes dans cette partie:
- L'argument `project=model.myProject` est inutile, en plus d'être inutilisable (techniquement), puisque chaque story déposée (drag n' drop) sera bien dans le projet en cours
- La zone est vide et ne fait pas le parcours des `stories` déjà présentes dans la `step`

```html
{{#each step.storiesInMe as |story|}}
    {{#draggable-item class="ui segment" activeClass="green inverted" content=story onClick="activate"}}
<!-- code HTML de chaque story -->
    {{/draggable-item}}
{{/each}}

**Comment by MathildeChan** [comment]
ça fonctionné  !! Merci beaucoup ! Il m'a suffit de remplacer le code par ce que vous m'avez donné
