### ISSUE TITLE
[Board][MoveStep] addToStep complexe

### ISSUE THREAD

**Issue by jcheron** [MathildeChan/ember-tds#5]
Le `addToStep` n'a pas besoin d'ajouter la story dans les stories de la step. et l'argument `project`inutile doit être supprimé.

https://github.com/MathildeChan/ember-tds/blob/600b70d0de6d6b43f682901b9e4895bc02702103/app/routes/project/board.js#L14

Il suffit comme je l'ai dit d'affecter la `step` au membre `step` de la `story`:
```php
  actions: {
      addToStep(story_id,step){
          this.get('store').findRecord('story',story_id).then((story)=>{
              set(story,'step',step);
              story.save().then(()=>{this.refresh();});
  });
```
Notez l'appel du refresh une fois la modification effectuée pour ne pas avoir à rafraîchir la page pour mettre à jour les données.

voir aussi https://github.com/MathildeChan/ember-tds/issues/4

**Comment by MathildeChan** [comment]
Je ne connaissais pas refresh(); c'est très utile ! Je teste ça dans la journée et je renverrais quelque chose ici si j'ai un problème

**Comment by MathildeChan** [comment]
Merci beaucoup pour la correction, cela fonctionne !
